version: '2'
services:
    ivcalculator-app:
        image: ivcalculator
        external_links:
            - ivcalculator-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ivcalculator?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ivcalculator-mysql:
        extends:
            file: mysql.yml
            service: ivcalculator-mysql
